top_level = source_file
case_sensitive = false

identifier         ::= standard ada_identifier
numeric_literal    ::= standard ada_numeric_literal
character_literal  ::= standard ada_character_literal
string_literal     ::= standard ada_string_literal
delimiter          ::= delimiters "&()+,;|"
symbol             ::= standard ada_symbol
comment            ::= standard ada_comment

format ';' no_space_before no_space_after new_line_after
format '.' no_space_before no_space_after
format '(' no_space_before no_space_after
format ')' no_space_before no_space_after
format 'is' new_line_after space_before
format 'do' new_line_after space_before
format ',' no_space_before space_after

format list_of_declarations indent_child

source_file ::= plugin_declaration

plugin_declaration ::= 'plugin' identifier 'version' version_spec 'is'
                          list_of_declarations
                       'end' identifier ';'

version_spec ::= < numeric_literal / '.' >

list_of_declarations ::= { declaration }

declaration ::= property_declaration | group_declaration

property_declaration ::= 'property' identifier [ 'inherited' ] ';'

group_declaration ::= 'group' identifier ':' identifier 'is'
   list_of_actions
   'end' identifier ';'

list_of_actions ::= { action_file_reference ';' }

action_file_reference ::= < identifier / '.' >
