before Compilation_Unit do
   --  IO.Put_Line ("Ada: loading cross references");
end;

after Compilation_Unit do
  --  IO.Put_Line ("Ada: finished cross references");
   --  Aqua.Report_State;
end;

before withed_unit_name do
   tree.withed_package := 0;
end;

after withed_unit_name/identifier do
   if parent.withed_package then
      parent.withed_package := parent.withed_package & "." & identifier.text;
   else
      parent.withed_package := identifier.text;
   end if;
   
   child.entity := Komnenos.Get_Entity (tree.withed_package, "package-declaration");
   
   if child.entity then
     parent.Entity := child.entity;
   
     Komnenos.Cross_Reference 
        (child, child.entity);
   end if;
end;

before defining_qualified_reference do
   tree.defined_entity :=
      tree^subprogram_declaration.defined_entity;
   if not tree.defined_entity then
      tree.error ("no defined entity for " & tree.image)
   end if;
end;

after defining_qualified_reference/identifier do
   if child.last then
      null;
   else
      child.entity := Komnenos.Get_Entity (child.full_name, "package-declaration");
      if child.entity then
         Komnenos.Cross_Reference
           (child, child.entity, parent.defined_entity);
      else
	     child.error("unknown package: " & child.text)
      end if;
   end if;
end;

before object_reference do
   
end;

before object_reference/direct_name do

end;

after direct_name/identifier do

end;
