after assignment_statement/object_reference do
   parent.type := child.object.type;
end;

before assignment_statement/expression do
   child.expected_type := new Array;
   child.expected_type.append (parent.type);
end;
