before class_declaration do
   for inherited in tree.class.inheritance.list loop
      inherited.tree := Aqua.load_object (inherited.name & ".aqua");
      inherited.class := inherited.tree.class;
   end loop;
   
   for client in tree.class.clients.list loop
      client.tree := aqua.load_object (client.name & ".aqua");
      if client.tree then
         client.class := client.tree.class;
      end if;
   end loop;
end;

after class_declaration do
end;
