for all loop
   case Tree is
      when Typeref =>
         if Interface_Typeref then
            .Ada_Name := Qualified_Identifier'Image & "_Interface";
         else
            .Ada_Name := Qualified_Identifier'Image;
         end if;
   end case;
end loop;
