@!aquarius:actionscript
@declare Package_Name : constant String := Top.Qualified_Name & ".Server";
@Set_Output (Ada_Specification_Name (Package_Name));
with Rose.Objects;

package [Package_Name] is

   procedure Start_Server
     (Server : not null access [Top.Interface_Class_Name]'Class
@for Base of Top.Bases loop
@   for P of Base.Subprograms loop
     ;[P/Identifier]_Cap : out Rose.Objects.Capability
@   end loop;
@end loop;
@for P of Top.Subprograms loop
     ;[P/Identifier]_Cap : out Rose.Objects.Capability
@end loop;
     );

end [Package_Name];
