@!aquarius:actionscript
@declare Qualified_Name : constant String :=
@   /Top_Level_Interface_Declaration/Qualified_Identifier.Image;
@declare Package_Name : constant String := Qualified_Name & ".Server";
@declare Base_Name : constant String :=
@   /Top_Level_Interface_Declaration/Qualified_Identifier.Last.Image;
@declare Interface_Name : constant String := Base_Name & "_Interface";
@declare Client_Record_Name : constant String := Base_Name & "_Client_Interface";
@declare Interface_Class_Name : constant String := "Root_" & Interface_Name;
@Set_Output (Ada_Specification_Name (Package_Name));
with Rose.Objects;

package [Package_Name] is

   procedure Start_Server
     (Server : not null access [Interface_Class_Name]'Class
@for /Top_Level_Interface_Declaration/List_Of_Declarations loop
@   case Tree is
@      when Subprogram_Declaration =>
     ;[/Identifier]_Cap : out Rose.Objects.Capability
@   end case;
@end loop;
     );

end [Package_Name];
