before database_declaration do
   IO.put_line ("checking");
end;

after database_declaration do
   IO.put_line ("done checking");
end;

after record_declaration/identifier do
   Komnenos.Define (parent, child.text, "record-declaration");
end;

after named_type/identifier do
   parent.entity := Komnenos.Get_Entity (identifier.text, "record-declaration");
end;

after data_field/named_type do
   parent.type := child.entity;
end;

after data_field do
   if not tree.type then
      tree.record_type := Komnenos.Get_Entity (tree/identifier.text, "record-declaration");
   end if;
end;