top_level ::= config_list
case_sensitive = false

identifier ::= regex "\l[\w_]*"
integer    ::= regex "\d+"
string     ::= regex "\x22[^\x22]*\x22"
delimiter  ::= delimiters "{};=:"
comment    ::= regex "--[.]*"

config_list ::= { config_item }

config_item ::= identifier config_entry

config_entry ::= nested_item | value_item

nested_item ::= '{' config_list '}'

value_item ::= '=' value ';'

value ::= identifier | integer | string


