compilation_unit ::= package_declaration
                     
case_sensitive = false

identifier         ::= standard ada_identifier
numeric_literal    ::= standard ada_numeric_literal
character_literal  ::= standard ada_character_literal
string_literal     ::= standard ada_string_literal
delimiter          ::= delimiters "&()+,;|"
symbol             ::= standard ada_symbol
comment            ::= standard ada_comment

format list_of_declarations indented_child

format ';' no_space_before no_space_after new_line_after
format '.' no_space_before no_space_after
format ',' no_space_before space_after

package_declaration ::=
   'package' qualified_identifier 'is' list_of_declarations 'end' qualified_identifier ';'
   
list_of_declarations ::= { declaration ';' }

declaration ::= option_declaration

option_declaration ::= identifier ':' type [ ':=' numeric_literal ] [ 'with' list_of_aspects ]

type ::= identifier

list_of_aspects ::= < aspect / ',' >

aspect ::= string_literal | character_literal

qualified_identifier ::= < identifier / '.' >
